### PR TITLE
Fix: Update Rust edition to 2024 ( latest ) and update as needed. (#1353)

### LINKED ISSUE #1353: Update Rust edition to 2024 ( latest ) and update as needed.

### PR DESCRIPTION
**Pull request by stservice**
## Summary

Updated the Rust edition for the `wasm_activation` crate from 2021 to 2024 (the
latest stable edition, supported since Rust 1.85+).

### Changes made

1. **`Cargo.toml`**: Updated `edition = "2021"` to `edition = "2024"`.
2. **`src/loss.rs`**: Updated macro fragment specifiers from `expr` to
   `expr_2021` in the `batch_8way_activation!` macro. Rust 2024 changes the
   `expr` specifier to also match `const` and `_` expressions; using `expr_2021`
   preserves the existing behaviour.
3. **`src/error.rs`**: Added explicit `unsafe {}` blocks around
   `raw_error_lane()` calls inside the `apply_calculate_error_batch_4way` unsafe
   function. In Rust 2024, the body of an `unsafe fn` is a safe context by
   default (`unsafe_op_in_unsafe_fn` lint is warn-by-default), so all unsafe
   operations require explicit `unsafe {}` blocks.
4. **WASM package rebuilt**: The `pkg/` artefacts were regenerated with the
   updated crate.

### Dependencies

`wasm-bindgen` (0.2.108) and `js-sys` (0.3.85) were already at the latest
versions and required no changes.

## Evidence

This is a backend/CLI change with no visual output. Evidence is provided via
test results:

- **128 Rust unit tests** pass (`cargo test` - all pass, 0 failures)
- **WASM build** succeeds with zero warnings
  (`wasm-pack build --target web --release`)
- **2156 Deno tests** pass (`quality.sh` - all pass, 0 failures)
- WASM binary compiles cleanly for `wasm32-unknown-unknown` target with
  `-D unsafe_op_in_unsafe_fn` (deny level) and zero warnings

## Test Plan

- All existing 128 Rust unit tests verify correctness after the edition
  migration
- All existing 2156 Deno integration/unit tests verify the WASM module works
  correctly end-to-end
- No new tests needed as this is a toolchain edition upgrade with no behavioural
  changes

> **Screenshot evidence not provided**: This appears to be a UI-related change but no screenshots were included. For UI changes, use Playwright MCP to capture screenshots as evidence: `browser_navigate` to open a relevant URL, then `browser_take_screenshot` to save to `docs/evidence/`.

---

## Automated Fix Details
This PR addresses issue #1353: **Update Rust edition to 2024 ( latest ) and update as needed.**

## Quality Checks
- Followed TDD methodology
- All new functionality has corresponding tests
- Ran `./quality.sh` - all checks pass

## Notes
- No existing tests were removed or commented out
- If any test modifications were required due to business logic changes, they are documented in the commits

Closes #1353

### CODE REVIEW

**Comment by stservice** [comment]
Thanks for the automated dependency review. No vulnerabilities, license issues, or OpenSSF Scorecard issues were found — all clear. No code changes needed.

**Comment by stservice** [comment]
All 2,147 tests pass with 0 failures, coverage is at 90.99%, and all modified lines are covered. No code changes needed — the automated test results confirm the PR is green and ready for merge.

File: wasm_activation/src/error.rs [hunk 1]
```diff
@@ -523,7 +524,7 @@ pub unsafe fn apply_calculate_error_batch_4way(
                 )
             };
             let e3 = if current_values[3] > 0.0 {
-                raw_error_lane(raw_error, 3)
+                unsafe { raw_error_lane(raw_error, 3) }
```
Comment (nleck) [inline wasm_activation/src/error.rs]: Why introduce "unsafe" ?

**Comment by nleck** [comment]
Why was "unsafe" introduced? Can we avoid "unsafe" as much as possible

**Comment by nleck** [comment]
Why was "unsafe" introduced? Can we avoid "unsafe" as much as possible

**Comment by stservice** [comment]
Good catch — the `unsafe` blocks were actually unnecessary.

WASM SIMD intrinsics (`f32x4_extract_lane`, etc.) are **safe functions** on the `wasm32` target (unlike x86 SIMD intrinsics which can have alignment issues). The original PR wrapped them in `unsafe` blocks because Rust 2024 changed `unsafe fn` bodies to no longer be implicitly unsafe, but the compiler confirms these operations don't need `unsafe` at all.

**Changes made:**
- Removed the `unsafe fn raw_error_lane` helper function entirely
- Removed all 4 `unsafe { raw_error_lane(...) }` call sites in the ReLU branch
- Replaced with direct safe `f32x4_extract_lane` calls
- Removed the now-unused `v128` import

Net result: **19 lines removed, 12 added** — less code, zero `unsafe` blocks introduced by this PR. Compiles cleanly with `-D warnings` and all 2156 tests pass.

**Comment by stservice** [comment]
Good catch — the `unsafe` blocks were unnecessary. WASM SIMD intrinsics like `f32x4_extract_lane` are safe functions on `wasm32` and don't need `unsafe`.

This has been fixed in commit 4b78d60a which removes the `raw_error_lane` unsafe helper entirely and replaces all 4 call sites with direct safe `f32x4_extract_lane` calls. The code compiles cleanly with `-D warnings`.

**Review by nleck — APPROVED** [review]

**Comment by stservice** [comment]
## Automated Processing Failed (First Attempt)

The automated worker encountered an issue while processing this comment and will retry.

### Failure Details
Claude timed out after 3600 seconds.

<details>
<summary>Last output from Claude (click to expand)</summary>

```
No output captured
```
</details>

### What happens next?
- This comment has been marked for retry (confused reaction added)
- The worker will attempt to process it again on the next scan
- If it fails again, manual intervention will be required
